version: '3.7'

services:
  atelier-admin-panel:
    container_name: admin-panel-service
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - frontend
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
networks:
  frontend:
    external: true
