# pull official base image
FROM node:lts-bullseye as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package*.json ./
RUN npm i -y
RUN npm i react-scripts -g --silent

# add app
COPY . ./

EXPOSE 3000
CMD ["npm", "run", "dev"]
